
"""Update schema to match current models

Revision ID: 1488dad4409f
Revises: 001
Create Date: 2026-03-13 15:21:48.311783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1488dad4409f'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_import_errors_id', table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_transfer_units_id', table_name='transfer_units')
    op.drop_table('transfer_units')
    op.drop_index('ix_imports_id', table_name='imports')
    op.drop_table('imports')
    op.drop_index('ix_transfers_id', table_name='transfers')
    op.drop_table('transfers')
    op.drop_index('ix_movements_id', table_name='movements')
    op.drop_table('movements')
    op.drop_index('ix_locations_id', table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_units_chassis_number', table_name='units')
    op.drop_index('ix_units_engine_number', table_name='units')
    op.drop_index('ix_units_id', table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('units_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('engine_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('chassis_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color',  sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('current_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'SOLD', 'IN_TRANSIT', name='unitstatus'), autoincrement=False, nullable=False),
    sa.Column('sold_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], name='units_current_location_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='units_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_units_id', 'units', ['id'], unique=False)
    op.create_index('ix_units_engine_number', 'units', ['engine_number'], unique=True)
    op.create_index('ix_units_chassis_number', 'units', ['chassis_number'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('locations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='locations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_locations_id', 'locations', ['id'], unique=False)
    op.create_table('movements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movement_type', postgresql.ENUM('IMPORT', 'SALE', 'TRANSFER', 'RETURN', 'DAMAGED', 'MAINTENANCE', name='movementtype'), autoincrement=False, nullable=False),
    sa.Column('from_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('movement_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], name='movements_from_location_id_fkey'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], name='movements_to_location_id_fkey'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name='movements_unit_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='movements_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='movements_pkey')
    )
    op.create_index('ix_movements_id', 'movements', ['id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('transfers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('from_location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_units', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transfer_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], name='transfers_from_location_id_fkey'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], name='transfers_to_location_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transfers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transfers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_transfers_id', 'transfers', ['id'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('imports_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('total_records', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('successful_imports', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_imports', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('import_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='imports_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='imports_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_imports_id', 'imports', ['id'], unique=False)
    op.create_table('transfer_units',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name='transfer_units_transfer_id_fkey'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name='transfer_units_unit_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transfer_units_pkey')
    )
    op.create_index('ix_transfer_units_id', 'transfer_units', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MANAGER', 'OPERATOR', 'VIEWER', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('import_errors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('raw_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name='import_errors_import_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='import_errors_pkey')
    )
    op.create_index('ix_import_errors_id', 'import_errors', ['id'], unique=False)
    # ### end Alembic commands ###
